version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: <%= Rails.application.credentials.dig(:development, :pg_username) %>
      POSTGRES_PASSWORD: <%= Rails.application.credentials.dig(:development, :pg_password) %>
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/TTO
    ports:
      - "3000:3000"
    depends_on:
      - db
